#!/usr/bin/env python
# coding: utf-8

# In[3]:


import pandas as pd
import numpy as np
import seaborn as sns


# In[4]:


import matplotlib.pyplot as plt
get_ipython().run_line_magic('matplotlib', 'inline')


# In[6]:


df = pd.read_csv('Store Sales.csv')


# In[7]:


df.info()


# In[9]:


# Changing the Datatypes from float to int


# In[12]:


df['Unit Price'] = df['Unit Price'].astype(int)


# In[15]:


df['Unit Cost'] = df['Unit Cost'].astype(int)


# In[18]:


df['Total Revenue'] = df['Total Revenue'].astype(int)


# In[21]:


df['Total Cost'] = df['Total Cost'].astype(int)


# In[23]:


df['Total Profit'] = df['Total Profit'].astype(int)


# In[24]:


df.head()


# In[26]:


df['Order Date'] = pd.to_datetime(df['Order Date'])


# In[27]:


df.head()


# # Exploratory Data Analysis using Matplotlib and Seaborn

# In[28]:


sns.set(style = 'whitegrid')


# In[59]:


plt.figure(figsize = (16,12))
sns.countplot(x = 'Region',data = df)
plt.title('Orders by Region', fontdict = {'fontweight':'bold', 'fontsize' : 22})


# - This chart shows the Total Orders by different Regions. The most orders were placed in Europe and the least orders were placed in North America

# In[71]:


plt.figure(figsize = (14,10))
plt.title('Total Cost by Each Item Type (in Millions)',fontdict = {'fontweight':'bold', 'fontsize' : 18})
sns.barplot(x = 'Item Type', y = 'Total Cost', data = df, estimator = sum)


# - The Total Cost for Office Supplies was the highest among all the Item Type sold in the store, The cost of producing Fruits 
# was the lowest.

# In[76]:


plt.figure(figsize = (14,10))
plt.title('Total Revenue by Each Item Type(in Millions)', fontdict = {'fontweight':'bold', 'fontsize' : 22})
sns.barplot(x = 'Item Type', y = 'Total Revenue', data = df, estimator = sum)


# - Revenue is the total amount of income generated by the sale of goods or services related to the company's primary operations.
# - Office supplies generated the maximum revenue of all the item types, followed by houselhold goods.

# In[81]:


labels = df['Sales Channel'].value_counts().index
explode = [0,0.05]
colors = ['Green','Orange']
values = df['Sales Channel'].value_counts().values


# In[84]:


plt.figure(figsize = (9,9))
plt.pie(values,explode = explode,colors = colors,labels = labels,autopct = '%1.1f%%')
plt.title('Percentage of Sales Channel Selected', fontdict = {'fontweight': 'bold', 'fontsize' : 20})


# - 52% of all the orders were placed Offline , 48% were placed online.

# In[91]:


plt.figure(figsize = (14,10))
plt.title('Total Units Sold by Each Item', fontdict = {'fontweight' : 'bold','fontsize': 18})
sns.barplot(x = 'Item Type', y = 'Units Sold',data = df, estimator = sum)


# - Beverages was sold the most out of all the item types and the least was Fruits.

# In[96]:


plt.figure(figsize = (14,12))
plt.title('Total Profit by Each Item', fontdict = {'fontweight' : 'bold','fontsize': 16})
sns.barplot(x = 'Item Type', y = 'Total Profit', data = df, estimator = sum)


# - Profits is the amount of income that remains after accounting for all expenses, debts, additional income streams and operating costs.
# - Cosmetics yielded the maximum profits out of all the Items and least profit was for Fruits

# In[102]:


plt.figure(figsize = (8,8))
df['Order Priority'].value_counts().plot(kind = 'bar')


# - Most of the orders priority was Low.

# In[104]:


plt.figure(figsize = (10,10))
sns.distplot(df['Total Revenue'])


# - Distplot shows the average disribution of the numerical column. In this case we chose Total Revenue. It can be seen most of
# the profit was between 0-1400000.

# In[107]:


plt.figure(figsize = (12,8))
sns.boxplot(x = 'Region',y = 'Units Sold', data = df)


# In[113]:


plt.figure(figsize = (14,10))
plt.title('Total Profit by Region', fontdict = {'fontweight' : 'bold', 'fontsize' : 16})
sns.barplot(x = 'Region', y = 'Total Profit', data = df, estimator = sum )


# - Europe had the maximum profits out of all the regions. The least profits were for the North America Region.

# In[122]:


sns.pairplot(df)


# # Interpretations
# 
# - Most Orders were from Europe.
# - Total Profit increased as the total units sold increased. There is a direct relation of Profit and Units sold.
# - People preferred to buy offline than order online. 52% in favour of buying it offline.
# - The most units sold was for Beverages, however, the Total Profits and the Total Revenue generated from it was the least of all items.
# - The Average profit was between 0-1400000 for all the items sold.
# - As Most Orders were from Europe, it can be seen that the Highest Profit was from Europe.

# In[ ]:




